import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { RepoData } from "~/interfaces";

const Repos: NextPage = () => {
  //   const { data: sessionData } = useSession();
  const { data: repoData } = api.repos.getRepos.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-grey-500 flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-2 px-4 py-16 ">
          Select a repo
          {repoData?.map((repo) => {
            return <ReposData key={repo.id} repo={repo} />;
          })}
        </div>
      </main>
    </>
  );
};

export default Repos;

const ReposData = (props: { repo: RepoData }) => {
  const { repo } = props;
  console.log(repo);
  return (
    <button className="w-1/2 bg-gray-800 py-2 px-2 text-white">
      <Link href={`/repo/${repo.owner}/${repo.repoName}`}>
        <h1>{repo.repoName}</h1>
      </Link>
    </button>
  );
};
