import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Repo: NextPage = () => {
  const router = useRouter();
  const { username, repo } = router.query;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-grey-500 flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-2 px-4 py-16 ">
          <h1>{username}</h1>
          <h1>{repo}</h1>
        </div>
      </main>
    </>
  );
};

export default Repo;
