import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { api } from "~/utils/api";

const Repo: NextPage = () => {
  const router = useRouter();
  const [username, setUserName] = useState<string>("");
  const [repo, setRepo] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    setLoading(true);
    if (router.isReady) {
      setUserName(router.query.username as string);
      setRepo(router.query.repo as string);
      setLoading(false);
    }
  }, [router]);
  // const { data: repoData } = api.repos.getRepoFiles.useQuery({
  //   username: username as string,
  //   repoName: repo as string,
  // });

  // console.log(repoData);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-grey-500 flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-2 px-4 py-16 ">
          <h1>{username}</h1>
          <h1>{repo}</h1>
        </div>
      </main>
    </>
  );
};

export default Repo;
